"""initial migration

Revision ID: b93826de6764
Revises: 
Create Date: 2024-08-27 05:16:44.293467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93826de6764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('team_division', sa.String(), nullable=True),
    sa.Column('unavailable', sa.Boolean(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('strength_overall_home', sa.Integer(), nullable=True),
    sa.Column('strength_overall_away', sa.Integer(), nullable=True),
    sa.Column('strength_attack_home', sa.Integer(), nullable=True),
    sa.Column('strength_attack_away', sa.Integer(), nullable=True),
    sa.Column('strength_defence_home', sa.Integer(), nullable=True),
    sa.Column('strength_defence_away', sa.Integer(), nullable=True),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('finished_provisional', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.String(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('provisional_start_time', sa.Boolean(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('team_a', sa.Integer(), nullable=True),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.Column('team_h', sa.Integer(), nullable=True),
    sa.Column('team_h_score', sa.Integer(), nullable=True),
    sa.Column('team_h_difficulty', sa.Integer(), nullable=True),
    sa.Column('team_a_difficulty', sa.Integer(), nullable=True),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deadline_time', sa.String(), nullable=True),
    sa.Column('release_time', sa.String(), nullable=True),
    sa.Column('average_entry_score', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('data_checked', sa.Boolean(), nullable=True),
    sa.Column('highest_scoring_entry', sa.Integer(), nullable=True),
    sa.Column('deadline_time_epoch', sa.Integer(), nullable=True),
    sa.Column('deadline_time_game_offset', sa.Integer(), nullable=True),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('is_previous', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_next', sa.Boolean(), nullable=True),
    sa.Column('cup_leagues_created', sa.Boolean(), nullable=True),
    sa.Column('h2h_ko_matches_created', sa.Boolean(), nullable=True),
    sa.Column('ranked_count', sa.Integer(), nullable=True),
    sa.Column('most_selected', sa.Integer(), nullable=True),
    sa.Column('most_transferred_in', sa.Integer(), nullable=True),
    sa.Column('top_element', sa.Integer(), nullable=True),
    sa.Column('chip_plays', sa.JSON(), nullable=True),
    sa.Column('top_element_info_id', sa.Integer(), nullable=True),
    sa.Column('top_element_info', sa.JSON(), nullable=True),
    sa.Column('transfers_made', sa.Integer(), nullable=True),
    sa.Column('most_captained', sa.Integer(), nullable=True),
    sa.Column('most_vice_captained', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('chance_of_playing_this_round', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('cost_change_event', sa.Integer(), nullable=True),
    sa.Column('cost_change_event_fall', sa.Integer(), nullable=True),
    sa.Column('cost_change_start', sa.Integer(), nullable=True),
    sa.Column('cost_change_start_fall', sa.Integer(), nullable=True),
    sa.Column('dreamteam_count', sa.Integer(), nullable=True),
    sa.Column('element_type', sa.Integer(), nullable=True),
    sa.Column('ep_next', sa.String(), nullable=True),
    sa.Column('ep_this', sa.String(), nullable=True),
    sa.Column('event_points', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('in_dreamteam', sa.Boolean(), nullable=True),
    sa.Column('news', sa.String(), nullable=True),
    sa.Column('news_added', sa.String(), nullable=True),
    sa.Column('now_cost', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('points_per_game', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('selected_by_percent', sa.String(), nullable=True),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.Column('squad_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('team_code', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('transfers_in', sa.Integer(), nullable=True),
    sa.Column('transfers_in_event', sa.Integer(), nullable=True),
    sa.Column('transfers_out', sa.Integer(), nullable=True),
    sa.Column('transfers_out_event', sa.Integer(), nullable=True),
    sa.Column('value_form', sa.String(), nullable=True),
    sa.Column('value_season', sa.String(), nullable=True),
    sa.Column('web_name', sa.String(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('own_goals', sa.Integer(), nullable=True),
    sa.Column('penalties_saved', sa.Integer(), nullable=True),
    sa.Column('penalties_missed', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('bps', sa.Integer(), nullable=True),
    sa.Column('influence', sa.String(), nullable=True),
    sa.Column('creativity', sa.String(), nullable=True),
    sa.Column('threat', sa.String(), nullable=True),
    sa.Column('ict_index', sa.String(), nullable=True),
    sa.Column('starts', sa.Integer(), nullable=True),
    sa.Column('expected_goals', sa.String(), nullable=True),
    sa.Column('expected_assists', sa.String(), nullable=True),
    sa.Column('expected_goal_involvements', sa.String(), nullable=True),
    sa.Column('expected_goals_conceded', sa.String(), nullable=True),
    sa.Column('influence_rank', sa.Integer(), nullable=True),
    sa.Column('influence_rank_type', sa.Integer(), nullable=True),
    sa.Column('creativity_rank', sa.Integer(), nullable=True),
    sa.Column('creativity_rank_type', sa.Integer(), nullable=True),
    sa.Column('threat_rank', sa.Integer(), nullable=True),
    sa.Column('threat_rank_type', sa.Integer(), nullable=True),
    sa.Column('ict_index_rank', sa.Integer(), nullable=True),
    sa.Column('ict_index_rank_type', sa.Integer(), nullable=True),
    sa.Column('corners_and_indirect_freekicks_order', sa.Integer(), nullable=True),
    sa.Column('corners_and_indirect_freekicks_text', sa.String(), nullable=True),
    sa.Column('direct_freekicks_order', sa.Integer(), nullable=True),
    sa.Column('direct_freekicks_text', sa.String(), nullable=True),
    sa.Column('penalties_order', sa.Integer(), nullable=True),
    sa.Column('penalties_text', sa.String(), nullable=True),
    sa.Column('expected_goals_per_90', sa.Integer(), nullable=True),
    sa.Column('saves_per_90', sa.Integer(), nullable=True),
    sa.Column('expected_assists_per_90', sa.Integer(), nullable=True),
    sa.Column('expected_goal_involvements_per_90', sa.Integer(), nullable=True),
    sa.Column('expected_goals_conceded_per_90', sa.Integer(), nullable=True),
    sa.Column('goals_conceded_per_90', sa.Integer(), nullable=True),
    sa.Column('now_cost_rank', sa.Integer(), nullable=True),
    sa.Column('now_cost_rank_type', sa.Integer(), nullable=True),
    sa.Column('form_rank', sa.Integer(), nullable=True),
    sa.Column('form_rank_type', sa.Integer(), nullable=True),
    sa.Column('points_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('points_per_game_rank_type', sa.Integer(), nullable=True),
    sa.Column('selected_rank', sa.Integer(), nullable=True),
    sa.Column('selected_rank_type', sa.Integer(), nullable=True),
    sa.Column('starts_per_90', sa.Integer(), nullable=True),
    sa.Column('clean_sheets_per_90', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fpl_id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('team_players',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_players')
    op.drop_table('managers')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('gameweeks')
    op.drop_table('fixtures')
    op.drop_table('clubs')
    # ### end Alembic commands ###
